language: python
deploy:
  provider: pypi
  user: noamelf
  password:
    secure: ETo4r94Vhme0oBzMiH0y4SAvVMeh+tXazxYGSX7BR44kV6xPgAE+gMGeALOM8B5a7d1uPzmPfRaULwGir7tUAZaLavaWFPVSAMzNgNm9430o9EDxt6tZoTReAnaAiIg2r3lp94c2hNaweUQf183gLLT/dEtfqcn+xx1oEI7HTUriJkWKWBtzlhgRQQ5XTESdG6gT1SdEAbdtzhMuJBJXxgucyFQ1pJZE1ugflPkXwwGx8Tn31XYtRxnxrnFyW2TI780bAp6lOzFec7MzfmB7js1h7yvnv4zoDZps/c+rWY2TUfU0e2zWCwmUmdtVkJxwlTBCZh7tXhOkqq63MvbqwJEZRiUvOlhwOW0hTnY8nQEtNIYW3z517ZrOF7+mUMGLxPrT9CYD75Vx6fHRZqayMxj3xH6ThhwcnuZ8nt/D5o27ToSGumXelPxd5I3jFRQaOhE+L0fZEzcrDzg+qGC69KV8YBzuSLBf+iEN3LTLqVYxoHcNJ+vLX0MDXwhbG79A8VoZ6w7iJu5HGHclqLwh3vtYQk0xPpX8wMzeTtS94xP8KBm9+ocfl9qFpfFpcGqpc7xWfwpwwh4gSDn0JXsj9SaHwhQWfzGx9IvXQZvVSgZMIjwf15APJ7YI9HwYZGYR5400pKyMbQo7CkQgqMj75rq8zraZZ7b2FqyY2OXGMy8=
